Update build-flaos-legacy.yml

diff --git a/.github/workflows/build-flaos-legacy.yml b/.github/workflows/build-flaos-legacy.yml
--- a/.github/workflows/build-flaos-legacy.yml
+++ b/.github/workflows/build-flaos-legacy.yml
@@ -1,6 +1,6 @@
 name: Build FlaOS legacy
 
-on: 
+on:
   release:
     types: [published]
   push:
@@ -8,8 +8,8 @@ on:
     - 'v*'
   #  branches: 
   #    - master
-#  schedule:
-#    - cron: 0 8 * * 5
+  #  schedule:
+  #    - cron: 0 8 * * 5
   watch:
     types: [started]
 
@@ -32,7 +32,6 @@ jobs:
     - name: Clone source code
       run: |
         git clone --depth=1 https://github.com/1280-720/fla-pdv-legacy.git /opt/rt-n56u
-        fi
         cd /opt/rt-n56u/toolchain-mipsel
         sh dl_toolchain.sh
         mkdir -p /opt/images/
@@ -42,13 +41,13 @@ jobs:
       run: |
         cd /opt/rt-n56u/trunk
         if [ ! -f configs/templates/$TNAME.config ] ; then
-        echo "configs/templates/$TNAME.config not found "
-        exit 1
+          echo "configs/templates/$TNAME.config not found "
+          exit 1
         fi
         cp -f configs/templates/$TNAME.config .config
         sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
         
-### Delete old configs ###        
+        ### Delete old configs ###        
         sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config
         sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config
         sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config
@@ -62,28 +61,27 @@ jobs:
         sed -i '/CONFIG_FIRMWARE_INCLUDE_SMARTDNS/d' .config
         sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
         sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
-        sed -i 's/ CONFIG_FIRMWARE_INCLUDE_GDUT_DRCOM/d' .config
-	sed -i 's/ CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config
-	sed -i 's/ CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' .config
-	sed -i 's/ CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' .config
-	sed -i 's/ CONFIG_FIRMWARE_INCLUDE_NAPT66/d' .config
-	sed -i 's/ CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config
-	sed -i 's/ CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config
-	sed -i 's/ CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config
-	sed -i 's/ CONFIG_FIRMWARE_INCLUDE_VLMCSD/d' .config
-	sed -i 's/ CONFIG_FIRMWARE_INCLUDE_TTYD/d' .config
-	sed -i 's/ CONFIG_FIRMWARE_INCLUDE_LRZSZ/d' .config
-	sed -i 's/ CONFIG_FIRMWARE_INCLUDE_HTOP/d' .config
-	sed -i 's/ CONFIG_FIRMWARE_INCLUDE_NANO/d' .config
-	sed -i 's/ CONFIG_FIRMWARE_INCLUDE_IPERF3/d' .config
-	sed -i 's/ CONFIG_FIRMWARE_INCLUDE_DUMP1090/d' .config
-	sed -i 's/ CONFIG_FIRMWARE_INCLUDE_RTL_SDR/d' .config
-	sed -i 's/ CONFIG_FIRMWARE_INCLUDE_MTR/d' .config
-	sed -i 's/ CONFIG_FIRMWARE_INCLUDE_SOCAT/d' .config
-	sed -i 's/CONFIG_FIRMWARE_INCLUDE_WIREGUARD/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_GDUT_DRCOM/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_NAPT66/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_VLMCSD/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_TTYD/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_LRZSZ/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_HTOP/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_NANO/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_IPERF3/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_DUMP1090/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_RTL_SDR/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_MTR/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_SOCAT/d' .config
+        sed -i 's/CONFIG_FIRMWARE_INCLUDE_WIREGUARD/d' .config
         
-### Define custom config ###
-
+        ### Define custom config ###
         echo "CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n" >> .config 
         echo "CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n" >> .config 
         echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=n" >> .config 
@@ -107,31 +105,31 @@ jobs:
         echo "CONFIG_FIRMWARE_INCLUDE_WYY=n" >> .config
         echo "CONFIG_FIRMWARE_INCLUDE_WYYBIN=n" >> .config # Include 4MB binary, else it will be downloaded and executed normally
         echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=n" >> .config #zerotier ~1.3M
-	echo "CONFIG_FIRMWARE_INCLUDE_GDUT_DRCOM=n" >> .config 
-	echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=y" >> .config 
-	echo "CONFIG_FIRMWARE_INCLUDE_MINIEAP=n" >> .config 
-	echo "CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n" >> .config 
-	echo "CONFIG_FIRMWARE_INCLUDE_NAPT66=n" >> .config 
-	echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n" >> .config 
-	echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n" >> .config 
-	echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n" >> .config 
-	echo "CONFIG_FIRMWARE_INCLUDE_VLMCSD=n" >> .config 
-	echo "CONFIG_FIRMWARE_INCLUDE_TTYD=n" >> .config 
-	echo "CONFIG_FIRMWARE_INCLUDE_LRZSZ=n" >> .config 
-	echo "CONFIG_FIRMWARE_INCLUDE_HTOP=y" >> .config
-	echo "CONFIG_FIRMWARE_INCLUDE_NANO=y" >> .config 
-	echo "CONFIG_FIRMWARE_INCLUDE_IPERF3=y" >> .config 
-	echo "CONFIG_FIRMWARE_INCLUDE_DUMP1090=n" >> .config 
-	echo "CONFIG_FIRMWARE_INCLUDE_RTL_SDR=n" >> .config 
-	echo "CONFIG_FIRMWARE_INCLUDE_MTR=n" >> .config 
-	echo "CONFIG_FIRMWARE_INCLUDE_SOCAT=n" >> .config 
-	echo "CONFIG_FIRMWARE_INCLUDE_WIREGUARD=n" >> .config 
-
-### Start building ###        
+        echo "CONFIG_FIRMWARE_INCLUDE_GDUT_DRCOM=n" >> .config 
+        echo "CONFIG_FIRMWARE_INCLUDE_DOGCOM=y" >> .config 
+        echo "CONFIG_FIRMWARE_INCLUDE_MINIEAP=n" >> .config 
+        echo "CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n" >> .config 
+        echo "CONFIG_FIRMWARE_INCLUDE_NAPT66=n" >> .config 
+        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=n" >> .config 
+        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=n" >> .config 
+        echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=n" >> .config 
+        echo "CONFIG_FIRMWARE_INCLUDE_VLMCSD=n" >> .config 
+        echo "CONFIG_FIRMWARE_INCLUDE_TTYD=n" >> .config 
+        echo "CONFIG_FIRMWARE_INCLUDE_LRZSZ=n" >> .config 
+        echo "CONFIG_FIRMWARE_INCLUDE_HTOP=y" >> .config 
+        echo "CONFIG_FIRMWARE_INCLUDE_NANO=y" >> .config 
+        echo "CONFIG_FIRMWARE_INCLUDE_IPERF3=y" >> .config 
+        echo "CONFIG_FIRMWARE_INCLUDE_DUMP1090=n" >> .config 
+        echo "CONFIG_FIRMWARE_INCLUDE_RTL_SDR=n" >> .config 
+        echo "CONFIG_FIRMWARE_INCLUDE_MTR=n" >> .config 
+        echo "CONFIG_FIRMWARE_INCLUDE_SOCAT=n" >> .config 
+        echo "CONFIG_FIRMWARE_INCLUDE_WIREGUARD=n" >> .config 
+        
+        ### Start building ###        
         sudo ./clear_tree
         sudo ./build_firmware_modify $TNAME 0
         sudo mv -f images/*.trx /opt/images/
-    - name : Upload packages
+    - name: Upload packages
       uses: actions/upload-artifact@master
       if: always()
       with:
